name: ${METRICBEAT_NAME}

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - core
      - diskio
      - filesystem
      - fsstat
    hostfs: /hostfs
  - module: docker
    metricsets:
      - container
      - cpu
      - diskio
      - healthcheck
      - info
      - memory
      - network
    hosts: [ unix:///var/run/docker.sock ]
    period: 10s

processors:
  - add_cloud_metadata: ~

monitoring:
  enabled: true
  elasticsearch:
    username: beats_system
    password: ${BEATS_SYSTEM_PASSWORD}

output.elasticsearch:
  hosts: [ "http://${METRICBEAT_HOST}:9200" ]
  username: metricbeat_internal
  password: ${METRICBEAT_INTERNAL_PASSWORD}

http:
  enabled: true
  host: 0.0.0.0