name: ${METRICBEAT_NAME}

metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

metricbeat.modules:
  - module: system
    period: 10s
    metricsets:
      - load
    hostfs: /hostfs

output.elasticsearch:
  hosts: [ "http://${METRICBEAT_HOST}:9200" ]
  username: metricbeat_internal
  password: ${METRICBEAT_INTERNAL_PASSWORD}

http:
  enabled: true
  host: 0.0.0.0
